### ISSUE TITLE
No Makefile as listed in the README

### ISSUE THREAD

**Issue by Baddaboo** [vanshg/MacAssistant#38]
> [Once cloned, cd into the grpc-swift directory, and run make.](https://github.com/vanshg/MacAssistant/blob/master/README.md)

**Comment by vanshg** [comment]
You've closed this issue, so I'm assuming you figured it out -- otherwise, all I can say is that there should be Makefile within the grpc-swfit directory (it is a submodule, so make sure to clone/pull recursively) unless the grpc-swift repo removes the Makefile (but that shouldn't be the case right now, as the submodule points to a specific commit)
